### ISSUE TITLE
Risk of getting blocked?

### ISSUE THREAD

**Issue by cmcfadden** [PatrickStankard/homebridge-fujitsu-airstage#19]
Super excited to try this project - thanks for you work. Only question - from the big HA thread, it seems like there have been issues with IPs getting banned due to polling too much. Any risk of that with this plugin?

**Comment by PatrickStankard** [comment]
Thanks! I have been using it since June and I haven’t had any issues. There is a local cache that is used to prevent polling the Airstage API for the state of the devices. The downside to this is that any changes made to the devices outside of Homebridge aren’t reflected.

**Comment by PatrickStankard** [comment]
I forgot to mention - there is a local cache that is used to prevent polling, but it is invalidated/refreshed every 5 minutes to ensure things that happen outside of Homebridge are reflected eventually.

I don't think there is a risk of getting blocked by the Airstage API, but if you have examples of it happening to you, I'd be happy to take a look to see what else can be done to prevent it from happening. I'm going to close this issue for now
